theme: jekyll-theme-minimal
title: Nekochan's Digital Diary
description: A personal space for memories and experiences
show_downloads: false
google_analytics: false
baseurl: /
frdshub_logo: /assets/images/frdshub-logo.jpg
frdshub_url: https://frdshub.com/
avatar: /assets/images/avatar.jpg
